### ISSUE TITLE
Theano backend not supported

### ISSUE THREAD

**Issue by sekarpdkt** [andreyzharkov/keras-monotonic-attention#1]
Looks like theano back end is not supported. gives error like
```

Using Theano backend.
Traceback (most recent call last):
  File "example.py", line 23, in <module>
    pos_emb = PositionEmbedding(max_time=1000, n_waves=20, d_model=40)(embedded)
  File "/ssd/anaconda3/lib/python3.6/site-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/ssd/MachineLearning/Python/NLP/keras-monotonic-attention/position_embedding.py", line 45, in call
    return K.tile(pos_enc, (samples, 1, 1))
  File "/ssd/anaconda3/lib/python3.6/site-packages/keras/backend/theano_backend.py", line 987, in tile
    if n.ndim == 0:
AttributeError: 'tuple' object has no attribute 'ndim'

```

**Comment by reyzharkov** [comment]
Yes, it is really not supported, everything was tested on tf only. And I am not planning to add another backends in the future 😞 but you may contribute

**Comment by sekarpdkt** [comment]
Will try to do it once, I am able to get hold of basic functionalities. Thanks.
